Formulario en reservaciones
AlanNoSauqui/Proyecto-Canchas pull request #50
Opened 2021-11-16 02:37 UTC by AlanNoSauqui

Se agregó el formulario en la página de reservaciones.

2021-11-16 02:39 UTC, AlanNoSauqui commented on views/js/calendar_functions.js
> +function mandarFormulario(){
Ésto no sé si sirva para mandar la info del formulario, pero lo puse de cualquier manera xd.

2021-11-16 07:59 UTC, jmcsuite requested changes

2021-11-16 07:59 UTC, jmcsuite commented on views/js/calendar_functions.js
> +function mandarFormulario(){
Pruebalo con la función sendData(), que esta en las lineas 150

2021-11-26 22:44 UTC, AlanNoSauqui commented
Cambios añadidos

2021-11-27 00:57 UTC, jmcsuite approved these changes

2021-11-27 00:58 UTC, merged